name: Deploy Javadoc

on:
  push:
    branches:
      - master
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy JavaDoc 🚀
        uses: CshCyberhawks/Javadoc-publisher.yml@1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: docs
          java-version: 11
          target-folder: .
          project: gradle
          custom-command: ./gradlew dokkaHtml
