name: Copy folder to other branch

on:
  push:
    branches:
      - main # Set a branch name to trigger deployment

jobs:
  copy:
    name: Copy my folder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy
        env:
          SRC_FOLDER_PATH: './src/main/kotlin/cshcyberhawks/swolib'
          TARGET_BRANCH: 'publish'
        run: |
          git config --global user.name 'cshrobotics2875'
          git config --global user.email 'cshrobotics@protonmail.com'
          cp -r $SRC_FOLDER_PATH ../src
          git checkout publish       # checkout to your branch
          mv -r ../src ./src
          git add -A
          git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)
          git push origin $TARGET_BRANCH # push to remote branch
